# Schema for the configuration files of the fontanalib_catalog_item module.

catalog_item.settings:
  type: config_object
  label: 'catalog_item settings'
  mapping:
    catalog_use_admin_theme:
      type: boolean
      label: 'Use administration theme when editing or creating catalog item content'

catalog_item.type.*:
  type: config_entity
  label: 'catalog_item type'
  mapping:
    name:
      type: label
      label: 'Name'
    type:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    help:
      type: text
      label: 'Explanation or submission guidelines'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
    preview_mode:
      type: integer
      label: 'Preview before submitting'
    display_submitted:
      type: boolean
      label: 'Display setting for author and date Submitted by post information'

# Plugin \Drupal\catalog_item\Plugin\Search\CatalogItemSearch
search.plugin.catalog_item_search:
  type: mapping
  label: 'Catalog search'
  mapping:
    rankings:
      type: sequence
      label: 'Content ranking'
      orderby: key
      sequence:
        type: integer
        label: 'Influence'

action.configuration.catalog_item_assign_owner_action:
  type: mapping
  label: 'Change the author of catalog item configuration'
  mapping:
    owner_uid:
      type: text
      label: 'Username'

action.configuration.catalog_item_unpromote_action:
  type: action_configuration_default
  label: 'Demote selected catalog items from front page configuration'

action.configuration.catalog_item_promote_action:
  type: action_configuration_default
  label: 'Promote selected catalog items from front page configuration'

action.configuration.catalog_item_make_sticky_action:
  type: action_configuration_default
  label: 'Make selected catalog items sticky configuration'

action.configuration.catalog_item_make_unsticky_action:
  type: action_configuration_default
  label: 'Make selected catalog items unsticky configuration'

action.configuration.catalog_item_unpublish_by_keyword_action:
  type: mapping
  label: 'Unpublish catalog items containing keyword(s) configuration'
  mapping:
    keywords:
      type: sequence
      label: 'Keywords'
      sequence:
        type: string
        label: 'Keyword'

block.settings.catalog_item_syndicate_block:
  type: block_settings
  label: 'Catalog Syndicate block'
  mapping:
    block_count:
      type: integer
      label: 'Block count'

condition.plugin.catalog_item_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string
